### ISSUE TITLE
Please add some demo instruction

### ISSUE THREAD

**Issue by weixelbaumer** [arillso/ansible.fqdn#2]
This role introduces no variables and has no usage examples?
Please add some comments to demo usage. TIA

**Comment by sbaerlocher** [comment]
Hello @weixelbaumer 

The role does not need a variable either, it works with `inventory_hostname` and `inventory_hostname_short` these are generated from gem inventory/hosts file generate. See: https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html#magic

**Comment by sbaerlocher** [comment]
Has your question been answered?

If I don't hear anything in the next 3 days I'll close the issues.
